const steps = [
{meta:'THE STARTING POINT',title:'Understand the problem.\nDefine the right first step.',description:'We get clear on your goals, your users, and what success looks like. Then we shape a focused scope around the work that will make the biggest difference.',deliverable:'A shared direction and a prioritized starting backlog',ai:'Supports research synthesis, explores requirements, and helps surface questions early. You and I set the priorities.'},
{meta:'A PLAN YOU CAN SEE',title:'Make the idea tangible.\nChoose a practical approach.',description:'We map the user journey, explore the interface, and choose an architecture that fits the project. The backlog becomes a clear, manageable plan for the first iteration.',deliverable:'A practical product design and an agreed sprint plan',ai:'Helps explore prototypes, compare approaches, and draft acceptance criteria. I validate the choices against your needs.'},
{meta:'PROGRESS IN SHORT CYCLES',title:'Build something real.\nLearn from every iteration.',description:'I develop in focused sprints, share working software, and use your feedback to refine what comes next. Priorities stay visible, and changes come with clear trade-offs.',deliverable:'Working increments, reviewed code, and regular demos',ai:'Assists with implementation, test cases, and documentation. I review, test, and take responsibility for the result.'},
{meta:'THE NEXT CHAPTER',title:'Launch with intention.\nKeep making it better.',description:'We prepare the release, check the critical journeys, and document how the system works. Real usage and feedback guide the next round of improvements.',deliverable:'A release plan, useful documentation, and next priorities',ai:'Helps draft release notes, summarize feedback, and investigate issues. Human review guides releases and follow-up work.'}
];
const tabs=[...document.querySelectorAll('[role="tab"]')];
function activateStep(index,focus=false){const step=steps[index];tabs.forEach((tab,i)=>{tab.setAttribute('aria-selected',String(i===index));tab.tabIndex=i===index?0:-1;tab.querySelector('.tab-mark').textContent=i===index?'−':'+';});document.querySelector('.panel-meta span').textContent=step.meta;document.getElementById('step-counter').textContent=`0${index+1} / 04`;const title=document.getElementById('step-title');title.replaceChildren();step.title.split('\n').forEach((line,i)=>{if(i)title.append(document.createElement('br'));title.append(document.createTextNode(line));});document.getElementById('step-description').textContent=step.description;document.getElementById('step-deliverable').textContent=step.deliverable;document.getElementById('step-ai').textContent=step.ai;document.getElementById('process-panel').setAttribute('aria-labelledby',tabs[index].id);if(focus)tabs[index].focus();}
tabs.forEach((tab,index)=>{tab.addEventListener('click',()=>activateStep(index));tab.addEventListener('keydown',e=>{let next;if(e.key==='ArrowDown'||e.key==='ArrowRight')next=(index+1)%tabs.length;if(e.key==='ArrowUp'||e.key==='ArrowLeft')next=(index+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();activateStep(next,true);}});});
const menu=document.querySelector('.menu-toggle');const mobileNav=document.getElementById('mobile-nav');function closeMenu(){mobileNav.hidden=true;menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation');}menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';mobileNav.hidden=open;menu.setAttribute('aria-expanded',String(!open));menu.setAttribute('aria-label',open?'Open navigation':'Close navigation');});mobileNav.querySelectorAll('a').forEach(link=>link.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});
const dialog=document.getElementById('brief-dialog');document.querySelectorAll('.brief-trigger').forEach(button=>button.addEventListener('click',()=>{closeMenu();dialog.showModal();document.body.style.overflow='hidden';}));document.querySelector('.close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{document.body.style.overflow='';});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
document.getElementById('brief-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target);const project=data.get('project').trim();const goal=data.get('goal').trim();if(!project||!goal){document.getElementById('form-status').textContent='Please add a project name and the problem you want to solve.';return;}const content=`PROJECT BRIEF\nggarciasoft\n\nProject / company: ${project}\nService: ${data.get('type')}\n\nThe problem to solve\n${goal}\n\nIdeal timing\n${data.get('timeline').trim()||'To be discussed'}\n\nQuestions for discovery\n- Who are the primary users?\n- Which features are essential for the first version?\n- What would a successful first release achieve?\n- Are there existing tools or systems to connect?\n- What budget and constraints should guide the scope?\n\nPrepared ${new Date().toLocaleDateString('en-US')}\nThis brief is downloaded locally. It has not been submitted or sent.\nYou can email it to ggarcia@ggarciasoft.com whenever you're ready.\n`;const url=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='ggarciasoft-project-brief.txt';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);const mailSubject=encodeURIComponent(`Project brief: ${project}`);const mailBody=encodeURIComponent(`Hi Gregory,\n\nI've prepared a project brief and would like to talk it through.\n\nProject / company: ${project}\n\nThanks.`);document.getElementById('form-status').innerHTML=`Your brief is ready to download. You can also <a href="mailto:ggarcia@ggarciasoft.com?subject=${mailSubject}&body=${mailBody}">email it to ggarcia@ggarciasoft.com</a> whenever you\u2019re ready.`;});
document.getElementById('year').textContent=new Date().getFullYear();
